stages:
  data_ingestion :
    cmd: python src/data_ingestion.py
    deps :
    - src/data_ingestion.py
    outs :
    - data/raw
    params :
    - data_ingestion.test_size
    - mongodb.CONNECTION_URL
    - mongodb.DB_NAME
    - mongodb.COLLECTION_NAME
  feature_engineering :
    cmd: python src/feature_engineering.py
    deps :
    - data/raw
    - src/feature_engineering.py
    outs :
    - data/feature_engineering
    - artifacts/Optimal_k.png
    - artifacts/cluster_metrics.json
    - artifacts/cluster_plots.png
  feature_selection :
    cmd : python src/feature_selection.py
    deps :
    - data/feature_engineering
    - src/feature_selection.py
    outs :
    - data/preprocess
    - artifacts/scaler.pkl
    - artifacts/power_transformer.pkl
    - artifacts/mi_feature_importance.png
  model_training :
    cmd : python src/model_training.py
    deps:
    - data/preprocess/x_train_processed.csv
    - data/preprocess/y_train_processed.csv
    outs: 
    - artifacts/xgb_model.pkl
    params:
    - model_training.model_type
    - model_training.params.n_estimators
    - model_training.params.learning_rate
    - model_training.params.max_depth
    - model_training.params.subsample
    - model_training.params.colsample_bytree
  model_evaluation :
    cmd : python src/model_evaluation.py
    deps: 
    - data/preprocess/x_test_processed.csv
    - data/preprocess/y_test_processed.csv
    outs:
    - artifacts/metrics.json
    - artifacts/confusion_matrix.png
    params:
    - model_training.model_type
    - model_training.params.n_estimators
    - model_training.params.learning_rate
    - model_training.params.max_depth
    - model_training.params.subsample
    - model_training.params.colsample_bytree
    - model_training.params.reg_lambda
    - model_training.params.reg_alpha
    - model_training.params.gamma
    - model_training.params.random_state
   

  
