stages:
  data_ingestion :
    cmd: python src/data_ingestion.py
    deps :
    - src/data_ingestion.py
    outs :
    - data/raw
  feature_engineering :
    cmd: python src/feature_engineering.py
    deps :
    - data/raw
    - src/feature_engineering.py
    outs :
    - data/feature_engineering
  feature_selection :
    cmd : python src/feature_selection.py
    deps :
    - data/feature_engineering
    - src/feature_selection.py
    outs :
    - data/preprocess
